[package]
name = "git_pocket_rest"
version = "0.1.0"
authors = ["Shane Qi <qizengtai@gmail.com>"]

[dependencies]
diesel = { version = "0.12.0", features = ["sqlite"] }
diesel_codegen = { version = "0.12.0", features = ["sqlite"] }
dotenv = "0.10.0"